server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/posttracking?serverTimezone=UTC
    username: postgres
    password: root
  jpa:
    show-sql: true
